<?php 
 return array (
  '南京' => '',
  '上海南京路店' => '',
  '南京路店' => '',
  'xxxxxxxxxxxxxxxxx' => '',
  'SHANGHAI' => '',
  'xxxxxxxx' => '',
  'Garden' => '',
  'Modernart' => '',
  'Ocean' => '',
  'Streetshot' => '',
  'Campaign' => '',
  'video1' => '',
  'video2' => '',
  'Monday 23 may' => '',
  '年轻OL的商务着装，可能太严肃，可能太时髦，或者像Lily这样正合适 作为年轻OL商务时装的开创者' => '',
  '上海市' => '',
  '徐汇区' => '',
  'Add' => '地址',
  'Tel' => '电话',
  'view_shop' => '查看门店',
  'view_map' => '查看地图',
);